# Generated by Django 5.0.6 on 2026-03-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_updated_by",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="todo",
                max_length=20,
            ),
        ),
    ]
